-- A numeric `id` on every catalog entity, while the UUID PK doubles as the
-- string `documentId`. Add a stable per-table numeric identity so reads can
-- expose both without reshaping the existing UUID-keyed schema.
ALTER TABLE catalog_clients ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE catalog_keywords ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE catalog_servers ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE catalog_media ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
